name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOCKER_IMAGE: 'melsabagh92/nodejsapp-1.33'
      K8S_NAMESPACE: 'default'

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Build Maven
      run: |
        # Add Maven build steps if required
        echo "Building Maven"

    - name: Build Docker Image
      run: |
        echo "Building Docker Image"
        docker build -t $DOCKER_IMAGE .

    - name: Deploy Docker Image
      run: |
        echo "Deploying Docker Image"
        echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u melsabagh92 --password-stdin
        docker push $DOCKER_IMAGE

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Find File in Workspace
      run: find $GITHUB_WORKSPACE -name "nodejsapp.yaml"
    - name: List Repository Contents
      run: ls -al $GITHUB_WORKSPACE
    - name: List Files in Working Directory
      run: |
       ls -al
       ls -al ../../jenkins-kubernetes-example
    - name: Deploy App on k8s
      run: |
        echo "Deploying App on k8s"
        kubectl apply -f ../../jenkins-kubernetes-example/nodejsapp.yaml
